### ISSUE TITLE
Panic at 'index out of bounds'

### ISSUE THREAD

**Issue by outfrost** [dalance/pipecolor#1]
Hi! Pipecolor looks like a tool that would be very useful to me, so I've decided to give it a go.

I have tried following the instructions in [README.md](blob/master/README.md) to create a simple rule that would colourise an entire line based on a regex.

My `~/.pipecolor.toml` is

```toml
[[lines]]
	pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*"
	colors = ["Magenta"]
	[[lines.tokens]]
		pat = ""
		colors = []
```

The file I'm testing it on contains these 2 lines

```
-- Some uninteresting message
This is a test message to see if VARIANT1 is colourised by pipecolor
```

Running `RUST_BACKTRACE=1 pipecolor --mode always test.log` results in

```
-- Some uninteresting message
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /build/rust/src/rustc-1.38.0-src/src/libcore/slice/mod.rs:2715:10
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: pipecolor::colorize::colorize
   8: pipecolor::output
   9: pipecolor::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
  15: __libc_start_main
  16: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Am I doing something wrong?

**Comment by dalance** [comment]
Thank you for your report.
Some color settings seem to be missing.
Could you try below?

```
[[lines]]
	pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*"
	colors = ["Magenta", "LightMagenta"]
	[[lines.tokens]]
		pat = ""
		colors = ["Yellow"]
```

`LightMagenta` corresponds to `(VARIANT1|VARIANT2|ETC)`,
and `Yellow` corresponds to `""`.
If you don't need tokens, tokens can be empty.

```
[[lines]]
	pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*"
	colors = ["Magenta", "LightMagenta"]
	tokens = []
```

I'll improve error message later.

**Comment by outfrost** [comment]
Thank you for the quick response!

It works as intended with this `~/.pipecolor.toml`
```toml
[[lines]]
	pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*"
	colors = ["Magenta", "Magenta"]
	tokens = []
```

Working off of the example in the readme, I didn't know `tokens` could be an empty list. Then again, I guess it's pretty basic TOML knowledge, so I shouldn't be surprised :)

IMHO there are 2 things that could be improved here. Configuration could be validated at program startup, before any input is processed, and capture groups without an explicitly assigned colour could use the last colour in the list. What do you think?

**Comment by outfrost** [comment]
Also, when I place a `$` at the end of that pattern to match the end of a line, i.e. the config line becomes

```toml
	pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*$"
```

pipecolor does not catch my test line any more. Removing `^` at the beginning of the pattern doesn't change it. Is there a regex quirk I'm missing here?

**Comment by dalance** [comment]
Thank you for your many suggestion!
I added empty tokens example in README, and added the two features about color setting.

* Configuration check at startup about each `colors` have one item at least.
* If capture group can't find an assigned color, the last color in the list is used.

**Comment by dalance** [comment]
About the regex problem, I can match like by below:

```
pat = "^This is a test message to see if (VARIANT1|VARIANT2|ETC).*\n$"
```

This regex follows https://docs.rs/regex/1.3.1/regex/#syntax.
By default, `.` don't match `\n` and `$` is end of text ( not `\n` ).
So `.*$` can't match `\n`.

Alternatively, `(?s)` can be used. If `(?s)` is specified, `.` match `\n`.

```
pat = "(?s)^This is a test message to see if (VARIANT1|VARIANT2|ETC).*$"
```

**Comment by dalance** [comment]
I release v0.4.1.

**Comment by outfrost** [comment]
Thank you for taking the time to explain all of this to me so thoroughly, and to implement the changes. I've just tested 0.4.2 and it's working very well. Great tool, thank you! :)
